name: Try me!
description: Create an Issue and get a Lorem Ipsum comment
title: "Try me!"
labels: ["try me"]
body:
  - type: markdown
    attributes:
      value: >
        Click "Submit new issue" and wait ~15s
  - type: textarea
    id: body
    attributes:
      label: Body
      placeholder: "You don't need to type anything here"
